pool:
  name: Azure Pipelines
steps:
  - task: Docker@0
    displayName: 'Build an image'
    inputs:
      azureSubscription: 'sercon-jdecode-x3'
      azureContainerRegistry: '{"loginServer":"jdecodex3.azurecr.io", "id" : "/subscriptions/a0c165fa-1553-4e7f-9042-adf184aa0f1e/resourceGroups/x-3/providers/Microsoft.ContainerRegistry/registries/jdecodex3"}'
      dockerFile: '**/AzurePipelines.Dockerfile'
      imageName: '$(Build.Repository.Name)'
      additionalImageTags: '$(Build.BuildId)'
      includeLatestTag: true

  - task: Docker@0
    displayName: 'Push an image'
    inputs:
      azureSubscription: 'sercon-jdecode-x3'
      azureContainerRegistry: '{"loginServer":"jdecodex3.azurecr.io", "id" : "/subscriptions/a0c165fa-1553-4e7f-9042-adf184aa0f1e/resourceGroups/x-3/providers/Microsoft.ContainerRegistry/registries/jdecodex3"}'
      action: 'Push an image'
      imageName: '$(Build.Repository.Name)'
      additionalImageTags: '$(Build.BuildId)'
      includeLatestTag: true

  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy: webapp-jdecode-x3'
    inputs:
      azureSubscription: 'sercon-jdecode-x3'
      appType: webAppContainer
      WebAppName: 'webapp-jdecode-x3'
      DockerNamespace: jdecodex3.azurecr.io
      DockerRepository: '$(Build.Repository.Name)'
      DockerImageTag: '$(Build.BuildId)'
