# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ac6dba23-45a6-4fc3-89ef-ff8f6d0142fc'
  imageRepository: 'jdecodex3'
  containerRegistry: 'jdecodex3.azurecr.io'
  dockerfilePath: '**/AzurePipelines.Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'sercon-jdecode-x3'
        appType: 'webAppContainer'
        WebAppName: 'webapp-jdecode-x3'
        deployToSlotOrASE: true
        ResourceGroupName: 'x-3'
        SlotName: 'production'
        DockerNamespace: 'jdecodex3.azurecr.io'
        DockerRepository: $(imageRepository)
        DockerImageTag: $(tag)
